import type { BraidManifest } from "../manifest/types.js";

export type CronJobSpec = {
  name: string;
  agentId: string;
  cron: string;
  session: "isolated";
  message: string;
};

function generateRoleReportPrompt(manifest: BraidManifest, roleId: string): string {
  const role = manifest.roles[roleId]!;
  const sections = manifest.reporting.daily.sections;
  const sectionsList = sections.map((s) => `## ${s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}`).join("\n\n");

  if (roleId === manifest.reporting.daily.summary_role) {
    return [
      `You are ${role.display_name} writing the daily executive summary.`,
      "",
      "Steps:",
      "1. Call report_read() to read all available role reports for today",
      "2. Synthesize them into the executive summary with these sections:",
      "",
      "## Company Snapshot",
      "## Key Wins",
      "## Risks And Blockers",
      "## Missing Reports",
      "## What Needs Human Attention",
      "## Tomorrow",
      "",
      "3. Call report_write(content: \"...\") to save the summary",
      "",
      "Be concise. Flag missing reports explicitly. Highlight anything that needs human action.",
    ].join("\n");
  }

  return [
    `You are ${role.display_name} writing your daily operational report.`,
    "",
    "Steps:",
    "1. Call wo_list() to review your active work orders",
    "2. Write your daily report with these sections:",
    "",
    sectionsList,
    "",
    "3. Call report_write(content: \"...\") to save your report",
    "",
    "Report only on your own lane. Be factual. \"Nothing material changed\" is valid, silence is not.",
  ].join("\n");
}

export function generateCronJobs(
  manifest: BraidManifest,
  opts: { baseHour?: number; intervalMinutes?: number } = {},
): CronJobSpec[] {
  const { daily } = manifest.reporting;
  if (!daily.enabled) return [];

  const baseHour = opts.baseHour ?? 17;
  const interval = opts.intervalMinutes ?? 2;

  return daily.order.map((roleId, index) => {
    const minute = index * interval;
    const hour = baseHour + Math.floor(minute / 60);
    const min = minute % 60;

    return {
      name: `daily-${roleId}`,
      agentId: roleId,
      cron: `${min} ${hour} * * *`,
      session: "isolated" as const,
      message: generateRoleReportPrompt(manifest, roleId),
    };
  });
}

export function generateCronCommands(jobs: CronJobSpec[]): string[] {
  return jobs.map((job) => {
    const msg = job.message.replace(/'/g, "'\\''");
    return `openclaw cron add --name '${job.name}' --cron '${job.cron}' --agent '${job.agentId}' --session ${job.session} --message '${msg}'`;
  });
}

export function generateCronScript(jobs: CronJobSpec[]): string {
  const lines = [
    "#!/usr/bin/env bash",
    "# Braid daily reporting cron jobs",
    "# Generated by braid setup-cron",
    "#",
    "# This script creates cron jobs in OpenClaw for daily reporting.",
    "# Each role reports in staggered order, with the summary role last.",
    "",
    "set -e",
    "",
  ];

  for (const job of jobs) {
    lines.push(`echo "Creating cron job: ${job.name} (${job.cron})""`);
    const msg = job.message.replace(/'/g, "'\\''");
    lines.push(
      `openclaw cron add \\`,
      `  --name '${job.name}' \\`,
      `  --cron '${job.cron}' \\`,
      `  --agent '${job.agentId}' \\`,
      `  --session ${job.session} \\`,
      `  --message '${msg}'`,
      "",
    );
  }

  lines.push('echo "All ${jobs.length} daily reporting cron jobs created."');
  return lines.join("\n");
}
